### ISSUE TITLE
TODO: vérif login

### ISSUE THREAD

**Issue by RaphAlreadyTaken** [RaphaelMontet/CERIGame#1]
Il faut vérifier que le fonctionnement du login correspond à ce qui est demandé dans le sujet:

- Demandé: accéder à une page _http://localhost:3131/login_, puis se log et récupérer les infos côté serveur (affichage console).

- Réalisé: accès à la page _http://localhost:3131_, redirection automatique vers _index.html_, puis saisie des infos et accès à la page _http://localhost:3131/login?login=bob&password=bobby_.

**Comment by Wiplex** [comment]
Looks ok
